import { createClient } from '@supabase/supabase-js';
// @ts-ignore
import { GoogleGenAI } from '@google/genai';
import { buildResearchPrompt, buildDatasetPrompt } from '@/lib/prompts';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || '';
const geminiApiKey = process.env.GEMINI_API_KEY || '';

const ai = new GoogleGenAI({ apiKey: geminiApiKey });

export async function processGeneration(topicId: string) {
  const supabase = createClient(supabaseUrl, supabaseServiceKey);

  const { data: topic } = await supabase
    .from('topics')
    .select('*')
    .eq('id', topicId)
    .single();

  if (!topic) throw new Error('Topic not found');

  try {
    // Mark as generating
    await supabase
      .from('topics')
      .update({
        status: 'generating',
        locked_at: new Date().toISOString(),
        last_attempt_at: new Date().toISOString(),
      })
      .eq('id', topicId);

    // 1. Primary Research
    const prompt = buildResearchPrompt(topic);
    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });
    
    const finalContent = response.text;
    if (!finalContent) throw new Error('Gemini returned empty content');

    // Create version
    const nextVersion = (topic.generation_attempts ?? 0) + 1;
    const { data: version, error: versionError } = await supabase
      .from('topic_versions')
      .insert({
        topic_id: topicId,
        version_number: nextVersion,
        content: finalContent,
        manual_review_notes: `Generated by Engine v1 — Module: ${topic.category}`,
      })
      .select()
      .single();

    if (versionError) throw versionError;

    await supabase
      .from('topics')
      .update({
        status: 'generated',
        current_version_id: version.id,
        generation_attempts: nextVersion,
        locked_at: null,
      })
      .eq('id', topicId);

    // 2. Practice Dataset (Background/Non-critical)
    try {
      const datasetPrompt = buildDatasetPrompt(topic);
      const datasetResponse = await ai.models.generateContent({
        model: 'gemini-2.0-flash',
        contents: datasetPrompt,
      });
      const rawJson = (datasetResponse.text || '').replace(/```json|```/g, '').trim();
      const parsed = JSON.parse(rawJson || '{}');

      await supabase.from('practice_datasets').insert({
        topic_id: topicId,
        title: parsed.title || `${topic.title} Practice Dataset`,
        description: parsed.description,
        file_type: 'json',
        preview_json: parsed,
        row_count: parsed.rows?.length || 0,
      });

      if (parsed.exercises?.length) {
        await supabase.from('topic_exercises').insert(
          parsed.exercises.map((ex: any) => ({
            topic_id: topicId,
            question: ex.question,
            expected_formula: ex.expected_formula,
            difficulty: ex.difficulty || 'medium',
            hint: ex.hint,
            explanation: ex.explanation,
          }))
        );
      }
    } catch (e) {
      console.error(`[Engine] Dataset generation failed for ${topicId}:`, e);
    }

    return { success: true };
  } catch (error: any) {
    console.error(`[Engine] Generation failed for ${topicId}:`, error.message);
    
    await supabase
      .from('topics')
      .update({
        status: 'failed',
        last_error: error.message,
        generation_attempts: (topic.generation_attempts ?? 0) + 1,
        locked_at: null,
      })
      .eq('id', topicId);

    throw error;
  }
}
