'use server';
// @ts-nocheck
import { createClient } from '@supabase/supabase-js';
import { revalidatePath } from 'next/cache';
// @ts-ignore
import { GoogleGenAI } from '@google/genai';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || '';
const geminiApiKey = process.env.GEMINI_API_KEY || '';

const ai = new GoogleGenAI({
  apiKey: geminiApiKey,
});

export async function triggerResearch(topicId: string) {
  if (!supabaseUrl || supabaseUrl === 'https://your-project.supabase.co') {
    return { success: false, error: 'Database not connected. Please provide real Supabase credentials.' };
  }
  
  const supabase = createClient(supabaseUrl, supabaseServiceKey);

  // 1. Fetch topic data
  const { data: topic } = await supabase
    .from('topics')
    .select('*')
    .eq('id', topicId)
    .single();

  if (!topic) {
    return { success: false, error: 'Topic not found' };
  }

  try {
    // Mark as generating
    await supabase
      .from('topics')
      .update({ status: 'generating', locked_at: new Date().toISOString(), last_attempt_at: new Date().toISOString() })
      .eq('id', topicId);

    const prompt = `Act as a senior Chartered Accountant (CA) from India. Write a comprehensive study guide (12-15 pages) on: "${topic.title}".

The guide is for a CA Intermediate student preparing for their first job interview. Use financial year 2024-25 for all tax rates, sections, and compliance deadlines. All GST rates, TDS sections, and limits must reflect the current Indian tax regime as of April 2024.

Structure:
1. Table of Contents (clickable anchors in markdown)
2. Concept explanation in plain professional language
3. 5-10 worked examples with step-by-step solutions using Indian standards (ICAI, Income Tax Act, GST Act)
4. 20 common interview Q&A with detailed model answers
5. Common practical mistakes to avoid
6. Quick-revision summary

Use Markdown. Use tables where helpful. Use ## for sections, ### for subsections.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });

    const finalContent = response.text;
    if (!finalContent) throw new Error('Gemini returned empty content');

    // Create version
    const nextVersion = (topic.generation_attempts ?? 0) + 1;
    const { data: version, error: versionError } = await supabase
      .from('topic_versions')
      .insert({
        topic_id: topicId,
        version_number: nextVersion,
        content: finalContent,
        manual_review_notes: 'Generated by Gemini 2.0 Flash',
      })
      .select()
      .single();

    if (versionError) throw versionError;

    await supabase
      .from('topics')
      .update({
        status: 'generated',
        current_version_id: version.id,
        generation_attempts: nextVersion,
        locked_at: null,
        interaction_id: null,
      })
      .eq('id', topicId);

    // 4. Generate Practice Dataset and Exercises (Secondary Flow)
    try {
      const datasetPrompt = `Generate a realistic practice dataset for the topic: "${topic.title}".

Return ONLY a JSON object in this exact shape, no markdown, no explanation:
{
  "title": "short dataset title",
  "description": "one sentence about the dataset",
  "columns": ["col1", "col2", "col3"],
  "rows": [
    ["val1", "val2", "val3"],
    ...
  ],
  "exercises": [
    {
      "question": "Write a VLOOKUP formula to...",
      "expected_formula": "=VLOOKUP(A2,Sheet2!A:C,2,0)",
      "difficulty": "medium",
      "hint": "Look at column B as the lookup value",
      "explanation": "This works because..."
    }
  ]
}

Generate 15-20 rows of realistic Indian accounting/business data relevant to ${topic.title}. Generate 5 exercises of varying difficulty.`;

      const datasetResponse = await ai.models.generateContent({
        model: 'gemini-2.0-flash',
        contents: datasetPrompt,
      });

      const rawJson = datasetResponse.text?.replace(/```json|```/g, '').trim();
      const parsed = JSON.parse(rawJson || '{}');

      await supabase.from('practice_datasets').insert({
        topic_id: topicId,
        title: parsed.title || `${topic.title} Practice Dataset`,
        description: parsed.description,
        file_type: 'json',
        preview_json: parsed,
        row_count: parsed.rows?.length || 0,
      });

      if (parsed.exercises?.length) {
        await supabase.from('topic_exercises').insert(
          parsed.exercises.map((ex: any) => ({
            topic_id: topicId,
            question: ex.question,
            expected_formula: ex.expected_formula,
            difficulty: ex.difficulty || 'medium',
            hint: ex.hint,
            explanation: ex.explanation,
          }))
        );
      }
    } catch (e) {
      console.error('Dataset generation failed (non-critical):', e);
      // Don't fail the whole generation if dataset parsing fails
    }

    revalidatePath('/admin');
    return { success: true };

  } catch (error: any) {
    await supabase
      .from('topics')
      .update({
        status: 'failed',
        last_error: error.message,
        generation_attempts: (topic.generation_attempts ?? 0) + 1,
        locked_at: null,
      })
      .eq('id', topicId);

    revalidatePath('/admin');
    return { success: false, error: error.message };
  }
}
