'use server';
// @ts-nocheck
import { createClient } from '@supabase/supabase-js';
import { revalidatePath } from 'next/cache';
// @ts-ignore
import { GoogleGenAI } from '@google/genai';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || '';
const geminiApiKey = process.env.GEMINI_API_KEY || '';

const ai = new GoogleGenAI({
  apiKey: geminiApiKey,
});

export async function triggerResearch(topicId: string) {
  if (!supabaseUrl || supabaseUrl === 'https://your-project.supabase.co') {
    return { success: false, error: 'Database not connected. Please provide real Supabase credentials.' };
  }
  
  const supabase = createClient(supabaseUrl, supabaseServiceKey);

  // 1. Idempotency Check & Atomic Lock
  const { data: topic, error: lockError } = await supabase
    .from('topics')
    .update({ 
      status: 'generating',
      locked_at: new Date().toISOString(),
      last_attempt_at: new Date().toISOString()
    })
    .eq('id', topicId)
    .in('status', ['queued', 'failed', 'delayed'])
    .select()
    .single();

  if (lockError || !topic) {
    return { success: false, error: 'Topic already processing or unavailable' };
  }

  try {
    // 2. Trigger Gemini Deep Research (Async)
    // Constructing a detailed prompt for the CA Junior persona
    const prompt = `Act as a senior Chartered Accountant (CA) from India. Conduct deep research and write a comprehensive study guide (12-15 pages) on the topic: "${topic.title}".
    
    The guide is for a CA Intermediate student preparing for their first job interview.
    
    Structure the guide as follows:
    1. Clickable Index / Table of Contents.
    2. Concept explanation in plain, professional language.
    3. 5-10 Worked examples with step-by-step solutions (relevant to Indian Tax/Accounting standards).
    4. 20 Common interview questions on this topic with detailed model answers.
    5. Common practical mistakes to avoid.
    6. Quick-revision summary at the end.
    
    Use Markdown formatting. Ensure all tax rates and section references are up-to-date for the current financial year in India.`;

    const interaction = await ai.interactions.create({
      input: prompt,
      agent: 'deep-research-pro-preview-12-2025',
      background: true,
      agentConfig: {
        thinkingSummaries: 'auto'
      }
    });

    // 3. Store interaction ID
    await supabase
      .from('topics')
      .update({ 
        interaction_id: interaction.id,
        locked_at: null 
      })
      .eq('id', topicId);

    revalidatePath('/admin');
    return { success: true, interactionId: interaction.id };

  } catch (error: any) {
    // 4. Handle Failure
    await supabase
      .from('topics')
      .update({ 
        status: 'failed',
        last_error: error.message,
        generation_attempts: (topic.generation_attempts ?? 0) + 1,
        locked_at: null 
      })
      .eq('id', topicId);

    revalidatePath('/admin');
    return { success: false, error: error.message };
  }
}

export async function syncResearchStatus(topicId: string) {
  if (!supabaseUrl || supabaseUrl === 'https://your-project.supabase.co') {
    return { success: false, error: 'Database not connected. Please provide real Supabase credentials.' };
  }

  const supabase = createClient(supabaseUrl, supabaseServiceKey);

  const { data: topic } = await supabase
    .from('topics')
    .select('*')
    .eq('id', topicId)
    .single();

  if (!topic || !topic.interaction_id) return { success: false, error: 'No active research found' };

  try {
    const interaction = await ai.interactions.get(topic.interaction_id);
    
    if (interaction.status === 'completed') {
      const finalContent = interaction.outputs[interaction.outputs.length - 1].text;

      // 1. Create New Version
      const { data: version, error: versionError } = await supabase
        .from('topic_versions')
        .insert({
          topic_id: topicId,
          version_number: (topic.current_version ?? 0) + 1,
          content: finalContent,
          manual_review_notes: 'Generated by Deep Research Agent'
        })
        .select()
        .single();

      if (versionError) throw versionError;

      // 2. Update Topic Status
      await supabase
        .from('topics')
        .update({ 
          status: 'generated',
          current_version: version.version_number,
          current_version_id: version.id,
          interaction_id: null // Clear once done
        })
        .eq('id', topicId);

      revalidatePath('/admin');
      return { success: true, status: 'completed' };
    } 
    
    if (interaction.status === 'failed') {
      await supabase
        .from('topics')
        .update({ 
          status: 'failed',
          last_error: interaction.error?.message || 'Unknown agent failure'
        })
        .eq('id', topicId);
      
      revalidatePath('/admin');
      return { success: false, status: 'failed', error: interaction.error };
    }

    return { success: true, status: interaction.status }; // Still in progress

  } catch (error: any) {
    return { success: false, error: error.message };
  }
}
